version: '2'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    networks:
      - minha-rede
  node:
    build:
      dockerfile: ./Dockerfile    
      context: .
    image: merciof/ecommerce-livro
    container_name: rural-books
    ports:
      - "80:3000"
    networks: 
      - minha-rede
    depends_on:
      - mongodb
networks:
  minha-rede:
    driver: bridge
