version: '3'
services:
  mongo:
    image: mongodb
    networks:
      - minha-rede
  node:
    build:
      dockerfile: ./Dockerfile    
      context: .
    image: merciof/ecommerce-livro
    container_name: rural-books
    ports:
      - 3000
    networks: 
      - minha-rede
    depends_on:
      - mongodb
networks:
  minha-rede:
    driver: bridge
